FROM node:20-alpine

# Manually ensure npm is present
# RUN apk add --no-cache npm

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

EXPOSE 5173
CMD ["npm", "run", "preview"]
